<?= $this->doctype(); ?>
<?php $usuario=$this->identity(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF-Admin')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('/_admin_template/css/pages/dashboard.css'))
        ->prependStylesheet($this->basePath('/_admin_template/css/style.css'))
        ->prependStylesheet($this->basePath('/_admin_template/css/font-awesome.css'))
        ->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600')
        ->prependStylesheet($this->basePath('/_admin_template/css/bootstrap-responsive.min.css'))
        ->prependStylesheet($this->basePath('/_admin_template/css/bootstrap.min.css'))
    ?>
  <style>

      #the_form {
          margin: 0;
          padding: 0;
      }
      .form_title_head{
          padding: 10px;
      }
      #the_form li{
          list-style: none;
          margin: 0 0 10px 0;
          padding: 8px;
      }

      #the_form li:hover, .form_title_head:hover{
          background: #EEE;
      }

      .form_ul{
          list-style: none;
          margin: 0;
          padding: 0;
      }

      #add_form_data label {
          font-weight: bold;
      }
  </style>
</head>
<body>
<?php extract($usuario);?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> </a><a class="brand" href="index.html">Bootstrap Admin Template </a>
            <div class="nav-collapse">
                <ul class="nav pull-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i
                                class="icon-cog"></i> Settings <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">Settings</a></li>
                            <li><a href="<?=$this->url('make');?>">Make</a></li>
                            <li><a href="javascript:;">Help</a></li>
                        </ul>
                    </li>
                    <?=$this->AcountMenu($usuario);?>
                </ul>
                <form class="navbar-search pull-right">
                    <input type="text" class="search-query" placeholder="Search">
                </form>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!-- /container -->
    </div>
    <!-- /navbar-inner -->
</div>
<!-- /navbar -->
<div class="subnavbar">
    <div class="subnavbar-inner">
        <div class="container">
            <ul class="mainnav">
                <li><a href="<?=$this->url('web');?>"><i class="icon-home"></i><span>Home Page</span> </a> </li>
                <li class="active"><a href="<?=$this->url('admin');?>"><i class="icon-dashboard"></i><span>Dashboard</span> </a> </li>
                <li><a href="reports.html"><i class="icon-list-alt"></i><span>Reports</span> </a> </li>
                <li><a href="guidely.html"><i class="icon-facetime-video"></i><span>App Tour</span> </a></li>
                <li><a href="charts.html"><i class="icon-bar-chart"></i><span>Charts</span> </a> </li>
                <li><a href="shortcodes.html"><i class="icon-code"></i><span>Shortcodes</span> </a> </li>
                <li class="dropdown"><a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-long-arrow-down"></i><span>Drops</span> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="icons.html">Icons</a></li>
                        <li><a href="faq.html">FAQ</a></li>
                        <li><a href="pricing.html">Pricing Plans</a></li>
                        <li><a href="login.html">Login</a></li>
                        <li><a href="signup.html">Signup</a></li>
                        <li><a href="error.html">404</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /container -->
    </div>
    <!-- /subnavbar-inner -->
</div>
<!-- /subnavbar -->

<div class="main">
    <div class="main-inner">
        <div class="container">
            <?php echo $this->content; ?>
        </div>

    </div>
</div>
<div class="extra">
    <div class="extra-inner">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <h4>
                        About Free Admin Template</h4>
                    <ul>
                        <li><a href="javascript:;">EGrappler.com</a></li>
                        <li><a href="javascript:;">Web Development Resources</a></li>
                        <li><a href="javascript:;">Responsive HTML5 Portfolio Templates</a></li>
                        <li><a href="javascript:;">Free Resources and Scripts</a></li>
                    </ul>
                </div>
                <!-- /span3 -->
                <div class="span3">
                    <h4>
                        Support</h4>
                    <ul>
                        <li><a href="javascript:;">Frequently Asked Questions</a></li>
                        <li><a href="javascript:;">Ask a Question</a></li>
                        <li><a href="javascript:;">Video Tutorial</a></li>
                        <li><a href="javascript:;">Feedback</a></li>
                    </ul>
                </div>
                <!-- /span3 -->
                <div class="span3">
                    <h4>
                        Something Legal</h4>
                    <ul>
                        <li><a href="javascript:;">Read License</a></li>
                        <li><a href="javascript:;">Terms of Use</a></li>
                        <li><a href="javascript:;">Privacy Policy</a></li>
                    </ul>
                </div>
                <!-- /span3 -->
                <div class="span3">
                    <h4>
                        Open Source jQuery Plugins</h4>
                    <ul>
                        <li><a href="http://www.egrappler.com">Open Source jQuery Plugins</a></li>
                        <li><a href="http://www.egrappler.com;">HTML5 Responsive Tempaltes</a></li>
                        <li><a href="http://www.egrappler.com;">Free Contact Form Plugin</a></li>
                        <li><a href="http://www.egrappler.com;">Flat UI PSD</a></li>
                    </ul>
                </div>
                <!-- /span3 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /extra-inner -->
</div>

<div class="footer">
    <div class="footer-inner">
        <div class="container">
            <div class="row">
                <div class="span12"> &copy; 2013 <a href="http://www.egrappler.com/">Bootstrap Responsive Admin Template</a>. </div>
                <!-- /span12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /footer-inner -->
</div>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('/_admin_template/js/base.js'))
            ->prependFile('/js/sprintf/jquery.sprintf.js')
            ->prependFile('/js/bootstrap.js')
            ->prependFile('/js/jquery-ui-1.9.1.custom.min.js')
            ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js') ?>
      <script>
          <?= $this->partial('/js/form/files/add.controller.js');?>
          <?= $this->partial('/js/form/files/add.view.js');?>
          <?= $this->partial('/js/form/files/add.form.js');?>
          <?= $this->partial('/js/form/files/add.model.js');?>
          <?= $this->partial('/js/form/files/add.repository.js');?>
          <?= $this->partial('/js/form/json.form.js');?>
          <?= $this->partial('/js/form/create.form.js');?>
          <?= $this->partial('/js/form/line.text.js');?>
          <?= $this->partial('/js/form/add.form.js');?>
          <?= $this->partial('/js/form/edit.form.js');?>
          <?= $this->partial('/js/json.js');?>
          <?= $this->partial('/js/form/parse.form.js');?>
      </script>



        <?php echo $this->inlineScript(); ?>
    </body>
</html>